name: Pandoc

on:
  push:
    paths:
      - '_posts/CV.markdown'

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: docker://pandoc/latex:2.9
        with:
          args: "/github/workspace/_posts/CV.markdown -s -o CV.pdf"