name: Pandoc

on:
  push:
    paths:
      - '_posts/2021-11-30-CV.markdown'

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pandoc/latex:2.16
        with:
          args: "/github/workspace/_posts/2021-11-30-CV.markdown -o CV.pdf"
      - uses: actions/upload-artifact@v2
        with:
          name: CV
          path: CV.pdf